export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';


export const FETCH_REQUEST = 'FETCH_REQUEST';
